### ISSUE TITLE
Preparation of Data

### ISSUE THREAD

**Issue by Karish6999** [rhobis/ConvergenceClubs#2]
Hello, 

I need help to work with my data. I have noticed that the excel sheet for GDP is in the format of Year(column) and Countries(headers). However, when you loaded it on R, it was reversed. 

I want to work with my data in the format, date (column) and markets(headers). How do i go about doing it? 

Will the other coding such as clustering and log t test be affected if I change the format? 

Any help at this stage will be much appreciated. 

Thank you

**Comment by rhobis** [comment]
Hi,
countryGDP.csv contains raw data, which are transformed by the script included in the countryGDP.R file to obtain the final data GDP.txt and filteredGDP.txt, which as you correctly stated have units in the rows and years as columns.

In order for the clustering procedure to work, data must be arranged such that each row represents a unit and each column represents a time period (year, month, etc...). I realized this wasn't specified in the manual, it will be added in the next releases.

To make function findClubs() work with your data you will need to transform it to satisfy the required format.

**Comment by Karish6999** [comment]
Hello, 

Thank you for your response. However, I am still encountering some issues when I followed the steps you mentioned. 

My filtered database thus transformed into 7 observations and 1397 variables (1397 dates over 7 markets).
The find clubs function is resulting as one club only. 

I am afraid this might be due to the way the data is arranged. My data looks different from that of the filtered GDP which had 152 observations over 35 variables (35 years over 152 countries). 

Can you please advise on it?

**Comment by rhobis** [comment]
If you arranged your data as required by the `findClubs()` function than it might just mean that your units do not form any club.

You can use function `estimateMod()` to check if all units converge prior to performing the clustering algorithm, you may read about how to do so in our paper here: https://journal.r-project.org/archive/2019/RJ-2019-021/RJ-2019-021.pdf

You could try to change some parameters in your `findClubs()` call and/or to filter your data differently, in any case it is data-related matter which does not depend on the package.
