### ISSUE TITLE
Error: Subscript `clubRows` has the wrong type `list`.

### ISSUE THREAD

**Issue by mbravidor** [rhobis/ConvergenceClubs#3]
Hey,

first of all, thanks for the great package! Using the `GDPfiltered` data works great. However, I encountered a problem when using my own test data (see attachment):

```
Error:
! Must subset rows with a valid subscript vector.
x Subscript `clubRows` has the wrong type `list`.
i It must be logical, numeric, or character.`
```

Code:

```
clubs1 <- findClubs(esg,
                    unit_names = 1,
                    dataCols = 2:11,
                    refCol = 11,
                    time_trim = 0.2,
                    cstar = 0,
                    cstar_method = "incremental",
                    cstar_increment = 0.05,
                    HACmethod = "FQSB")
```

For a while it worked without the `unit_names` argument but since the last RStudio update I get the following error:

```
Error:
! Assigned data `as.character(X[, unit_names])` must be compatible with existing data.
x Existing data has 50 rows.
x Assigned data has 0 rows.
i Only vectors of size 1 are recycled.`
```

Any idea what's wrong here? Any help is kindly appreciated!

[sample.csv](https://github.com/rhobis/ConvergenceClubs/files/8952735/sample.csv)

**Comment by rhobis** [comment]
The object passed to argument 'X' should be a dataframe.
Please try the following before using findClubs():

`esg <- as.data.frame(esg)`
