### ISSUE TITLE
ConvergenceClubs Package- High t value gets high P value also

### ISSUE THREAD

**Issue by ayyoobsm** [rhobis/ConvergenceClubs#4]
clubs <- findClubs(a, dataCols=2:39, unit_names = 1, refCol=2,HACmethod="AQSB",cstar_method = "fixed")
> clubs
======================================================================== 
club 1
------------------------------------------------------------------------ 
TVM, PTA, KTM, KLM, EKM, PGT, WYD

beta:      0.4517 
std.err:   0.1121 
tvalue:    4.0281 
pvalue:    1 
cstar:     0 

======================================================================== 
club 2
------------------------------------------------------------------------ 
KNR, ALP, KSGD, MLP, TCR, KKD

beta:      2.957 
std.err:   0.2374 
tvalue:    12.4577 
pvalue:    1 
cstar:     0 

======================================================================== 
divergent
------------------------------------------------------------------------ 
IDK          

here even though High t values are there, I am getting P values 1

**Comment by rhobis** [comment]
The log t-test by Phillips and Sul is a left one-tailed test with threshold -1.65 (the null hyphotesys is rejected if t<-1.65, and as per step 2 their algorithm the club is formed if t>-1.65, so basically a group is formed when the null is not rejected, so p-value > 5%). For this reason, in function estimateMod() we use Pr(T<t) to calculate the pvalue, and a p-value >0.05 is a sign that the rule for creating a club is satisfied.

Anyway, the pvalue does not affect the results, as the t-value is used in the algorithm to form clubs.


References:
https://github.com/rhobis/ConvergenceClubs/blob/master/R/estimateMod.R
Sichera, R.; Pizzuto, P., 2019. ConvergenceClubs: A Package for Performing the Phillips and Sul’s
Club Convergence Clustering Procedure. The R Journal
Phillips, P. C.; Sul, D., 2007. Transition modeling and econometric convergence tests. Economet-
rica 75 (6), 1771-1855.
Phillips, P. C.; Sul, D., 2009. Economic transition and growth. Journal of Applied Econometrics 24
(7), 1153-1185
